# Generated by Django 5.2.4 on 2025-07-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='email_content',
            field=models.TextField(blank=True),
        ),
    ]
