# Generated by Django 5.2.4 on 2025-07-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0002_template_email_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='email_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
