# Generated by Django 5.2.4 on 2025-07-25 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0003_alter_template_email_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='name',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='template',
            name='email_content',
        ),
        migrations.AddField(
            model_name='template',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='portalapp.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='template_type',
            field=models.CharField(default='Slice', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
