# Generated by Django 5.2.4 on 2025-07-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0006_noticelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticelog',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='notices/%Y-%m-%d/'),
        ),
    ]
