# Generated by Django 5.2.4 on 2025-07-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0007_noticelog_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticelog',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='notices/'),
        ),
    ]
