# Generated by Django 5.2.4 on 2025-07-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0008_alter_noticelog_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticelog',
            name='user_friendly_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
